micronaut:
  application:
    name: medical-call-center-api
  server:
    port: 8080
    max-request-size: '10MB'
    multipart:
      max-file-size: '10MB'
    cors:
      enabled: true

  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /main/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    intercept-url-map:
      - pattern: "/api/**"
        httpMethods: [ GET, POST, PUT, DELETE ]

  security:
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            secret: pGQBb6zEGh/RUcAYPDNbiopn0polsyfCy3C9RmdiXMAY/p0aNSQRlsszywVVSnz2
          refresh-token:
            expiration: 604800
            secret: pGQBb6zEGh/RUcAYPDNbiopn0polsyfCy3C9RmdiXMAY/p0aNSQRlsszywVVSnz2
      generator:
        access-token:
          expiration: 10

flyway:
  datasources:
    default:
      enabled: true


datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/medical_call_center?preparedStatementCacheQueries=0
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES


javamail:
  authentication:
    username: 'galixan@mail.ru'
    password: 'b71dwtfm8wuq9Xh7xeV5'
  properties:
    mail:
      smtp:
        port: 465
        auth: true
        starttls:
          enable: false
        ssl:
          enable: true
          trust: smtp.mail.ru
        host: smtp.mail.ru

