micronaut:
  application:
    name: vostok-shop-survey-api
  server:
    port: 8080
    max-request-size: '10MB'
    multipart:
      max-file-size: '10MB'
    cors:
      enabled: true

  router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /main/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    intercept-url-map:
      - pattern: "/api/**"
        httpMethods: [ GET, POST, PUT, DELETE ]

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pGQBb6zEGh/RUcAYPDNbiopn0polsyfCy3C9RmdiXMAY/p0aNSQRlsszywVVSnz2
      generator:
        access-token:
          expiration: 172800 #2 days


flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vostok_shop_survey?preparedStatementCacheQueries=0
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES


