CREATE OR REPLACE VIEW organization_category_view AS
SELECT
      organization_,
      type_,
      EXTRACT(YEAR FROM appeal_date_)  AS year_,
      EXTRACT(MONTH FROM appeal_date_) AS month_,
      (CASE WHEN category_ = 1  THEN 1 ELSE NULL::integer END) AS "1",
      (CASE WHEN category_ = 2  THEN 1 ELSE NULL::integer END) AS "2",
      (CASE WHEN category_ = 3  THEN 1 ELSE NULL::integer END) AS "3",
      (CASE WHEN category_ = 4  THEN 1 ELSE NULL::integer END) AS "4",
      (CASE WHEN category_ = 5  THEN 1 ELSE NULL::integer END) AS "5",
      (CASE WHEN category_ = 6  THEN 1 ELSE NULL::integer END) AS "6",
      (CASE WHEN category_ = 7  THEN 1 ELSE NULL::integer END) AS "7",
      (CASE WHEN category_ = 8  THEN 1 ELSE NULL::integer END) AS "8",
      (CASE WHEN category_ = 9  THEN 1 ELSE NULL::integer END) AS "9",
      (CASE WHEN category_ = 10 THEN 1 ELSE NULL::integer END) AS "10",
      (CASE WHEN category_ = 11 THEN 1 ELSE NULL::integer END) AS "11",
      (CASE WHEN category_ = 12 THEN 1 ELSE NULL::integer END) AS "12",
      (CASE WHEN category_ = 13 THEN 1 ELSE NULL::integer END) AS "13",
      (CASE WHEN category_ = 14 THEN 1 ELSE NULL::integer END) AS "14",
      (CASE WHEN category_ = 15 THEN 1 ELSE NULL::integer END) AS "15",
      (CASE WHEN category_ = 16 THEN 1 ELSE NULL::integer END) AS "16",
      (CASE WHEN category_ = 17 THEN 1 ELSE NULL::integer END) AS "17",
      (CASE WHEN category_ = 18 THEN 1 ELSE NULL::integer END) AS "18",
      (CASE WHEN category_ = 19 THEN 1 ELSE NULL::integer END) AS "19",
      (CASE WHEN category_ = 20 THEN 1 ELSE NULL::integer END) AS "20",
      (CASE WHEN category_ = 21 THEN 1 ELSE NULL::integer END) AS "21",
      (CASE WHEN category_ = 22 THEN 1 ELSE NULL::integer END) AS "22",
      (CASE WHEN category_ = 23 THEN 1 ELSE NULL::integer END) AS "23",
      (CASE WHEN category_ = 24 THEN 1 ELSE NULL::integer END) AS "24",
      (CASE WHEN category_ = 25 THEN 1 ELSE NULL::integer END) AS "25",
      (CASE WHEN category_ = 26 THEN 1 ELSE NULL::integer END) AS "26",
      (CASE WHEN category_ = 27 THEN 1 ELSE NULL::integer END) AS "27",
      (CASE WHEN category_ = 28 THEN 1 ELSE NULL::integer END) AS "28",
      (CASE WHEN category_ = 29 THEN 1 ELSE NULL::integer END) AS "29",
      (CASE WHEN category_ = 30 THEN 1 ELSE NULL::integer END) AS "30",
      (CASE WHEN category_ = 31 THEN 1 ELSE NULL::integer END) AS "31",
      (CASE WHEN category_ = 32 THEN 1 ELSE NULL::integer END) AS "32",
      (CASE WHEN category_ = 33 THEN 1 ELSE NULL::integer END) AS "33",
      (CASE WHEN category_ = 34 THEN 1 ELSE NULL::integer END) AS "34",
      (CASE WHEN category_ = 35 THEN 1 ELSE NULL::integer END) AS "35",
      (CASE WHEN category_ = 36 THEN 1 ELSE NULL::integer END) AS "36",
      (CASE WHEN category_ = 37 THEN 1 ELSE NULL::integer END) AS "37"
FROM appeal a;